language: elixir
sudo: false
elixir:
  - 1.7
  - 1.8
otp_release:
  - 21.3
services:
  - postgresql
cache:
  directories:
    - ~/.mix
    - ~/.hex
    - deps
    - _build
env:
  - MIX_ENV=test
before_script:
  - psql -c "CREATE DATABASE oban_test;" -U postgres
  - mix ecto.create -r Oban.Test.Repo
  - mix ecto.migrate -r Oban.Test.Repo
script:
  - mix test
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: credo
      env:
        - MIX_ENV=dev
      script: mix credo --strict
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
