version: 2
jobs:
  build:
    parallelism: 1

    docker:
      - image: circleci/elixir:1.8.1
        environment:
          DATABASE_URL: postgresql://postgres@localhost/oban_test
          MIX_ENV: test

      - image: circleci/postgres:11.1-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: oban_test

    working_directory: ~/repo

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - restore_cache:
          keys:
            - v1-plt-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-plt-cache-{{ .Branch }}
            - v1-plt-cache

      - run: mix do deps.get, compile
      - run: mix dialyzer --plt

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: deps
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: deps
      - save_cache:
          key: v1-mix-cache
          paths: deps
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: _build
      - save_cache:
          key: v1-build-cache
          paths: _build
      - save_cache:
          key: v1-plt-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - ~/.mix
      - save_cache:
          key: v1-plt-cache-{{ .Branch }}
          paths:
            - _build
            - ~/.mix
      - save_cache:
          key: v1-plt-cache
          paths:
            - _build
            - ~/.mix

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix ecto.migrate -r Oban.Test.Repo

      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix test
      - run: mix dialyzer --halt-exit-status
